defaults: &defaults
  adapter: mysql2
  encoding: utf8
  host: localhost
  reconnect: false

db_first:
  database: db_first
  username: root
  password: ''
  <<: *defaults

db_second:
  database: db_second
  username: root
  password: ''
  <<: *defaults

db_target:
  database: db_target
  username: root
  password: ''
  <<: *defaults
